const http = require("http");

const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Team Task Manager</title>
  <style>
    *{box-sizing:border-box}body{margin:0;background:#f5f7fb;color:#172033;font-family:Inter,system-ui,Segoe UI,sans-serif}button,input,select,textarea{font:inherit}button{cursor:pointer}
    .auth{min-height:100vh;display:grid;grid-template-columns:1.1fr .9fr}.hero{display:flex;align-items:flex-end;padding:56px;color:white;background:linear-gradient(135deg,rgba(18,64,92,.88),rgba(30,92,78,.75)),url("https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1500&q=80");background-size:cover;background-position:center}.hero h1{max-width:760px;margin:10px 0 18px;font-size:56px;line-height:1.03}.hero p{max-width:640px;color:rgba(255,255,255,.88);font-size:18px;line-height:1.7}.panel{display:flex;flex-direction:column;justify-content:center;gap:20px;background:white;padding:42px}.tabs{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:6px;background:#eef2f6;border-radius:8px}.tabs button,.profile button{border:0;border-radius:6px;min-height:40px;background:transparent;font-weight:900}.tabs .on{background:white;box-shadow:0 8px 20px rgba(19,33,52,.08)}form{display:grid;gap:12px}label{display:grid;gap:7px;color:#5b6473;font-size:13px;font-weight:800}input,textarea,select{width:100%;border:1px solid #d8dee8;border-radius:7px;background:white;color:#172033;min-height:42px;padding:10px 12px;outline:none}textarea{min-height:72px;resize:vertical}.primary{border:0;border-radius:7px;min-height:44px;background:#0b6bcb;color:white;font-weight:900}.msg{color:#775016;background:#fff4da;border-radius:999px;padding:8px 12px;font-weight:800;display:inline-block}
    .app{min-height:100vh;padding:28px}.top{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:20px}.eyebrow{margin:0;color:#0b6bcb;font-size:12px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.top h1{margin:4px 0 0;font-size:32px}.profile{display:flex;align-items:center;gap:10px;padding:8px;border:1px solid #dfe5ee;border-radius:8px;background:white}.profile b{border-radius:999px;background:#e9f7f0;color:#0b6848;padding:7px 10px;text-transform:capitalize}.profile button{background:#172033;color:white;padding:0 14px}
    .metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:18px}.metric{border:1px solid #e1e7ef;border-radius:8px;background:white;padding:18px}.metric span{display:block;color:#697386;font-size:13px;font-weight:800}.metric b{display:block;margin-top:8px;font-size:34px}.danger b{color:#c73b2f}.grid{display:flex;gap:18px}.side{width:320px;display:grid;align-content:start;gap:16px;border:1px solid #e1e7ef;border-radius:8px;background:white;padding:16px}.main{min-width:0;flex:1;border:1px solid #e1e7ef;border-radius:8px;background:white;padding:18px}.head{display:flex;justify-content:space-between;gap:16px;margin-bottom:16px}.head h2{margin:0;font-size:22px}.head p{margin:5px 0 0;color:#697386}.projects{display:grid;gap:8px}.projects button{display:grid;gap:4px;border:1px solid #e1e7ef;border-radius:8px;background:white;color:#172033;text-align:left;padding:12px}.projects .sel{border-color:#0b6bcb;background:#f0f7ff}.manage{display:grid;grid-template-columns:.9fr 1.1fr;gap:16px;margin-bottom:18px}.box{border:1px solid #e1e7ef;border-radius:8px;padding:14px;background:#fbfcfe}.members{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:12px}.members span{border:1px solid #dae1eb;border-radius:999px;background:white;padding:8px 10px;font-weight:800}.members small{margin-left:7px;color:#0b6bcb}.inline{grid-template-columns:1fr 115px 64px}.inline button{border:0;border-radius:7px;background:#172033;color:white;font-weight:900}.taskform{grid-template-columns:repeat(2,1fr)}.taskform textarea,.taskform button{grid-column:1/-1}.board{display:grid;grid-template-columns:repeat(4,minmax(210px,1fr));gap:12px;overflow-x:auto}.col{min-height:330px;border-radius:8px;background:#f4f6f9;padding:10px}.col h3{display:flex;justify-content:space-between;margin:4px 4px 12px;font-size:15px}.card{display:grid;gap:10px;border:1px solid #e1e7ef;border-radius:8px;background:white;padding:12px;margin-bottom:10px;box-shadow:0 10px 24px rgba(23,32,51,.06)}.card p{margin:0;color:#5b6473;font-size:13px;line-height:1.5}.row{display:flex;justify-content:space-between;gap:10px}.pill{border-radius:999px;padding:4px 8px;font-size:11px;font-weight:900}.low{background:#e9f7f0;color:#0b6848}.medium{background:#fff4da;color:#775016}.high{background:#ffe9e4;color:#a43828}.meta{color:#697386;font-size:12px;font-weight:800}.empty{color:#697386}
    @media(max-width:980px){.auth{display:block}.hero{min-height:48vh;padding:34px}.hero h1{font-size:40px}.grid,.manage{display:grid}.side{width:auto}.metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:620px){.app,.panel{padding:18px}.top,.profile{align-items:stretch;flex-direction:column}.metrics,.inline,.taskform{grid-template-columns:1fr}}
  </style>
</head>
<body><div id="root"></div>
<script>
const API="/api";
let token=localStorage.getItem("ttm_token")||"", user=null, projects=[], users=[], tasks=[], dash={total_projects:0,total_tasks:0,assigned_to_me:0,overdue:0,by_status:{todo:0,in_progress:0,review:0,done:0},tasks:[]}, selected=null, mode="signup", msg="";
const status={todo:"To do",in_progress:"In progress",review:"Review",done:"Done"}, pri={low:"Low",medium:"Medium",high:"High"};
async function req(path, opts={}){const r=await fetch(API+path,{method:opts.method||"GET",headers:{"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{})},body:opts.body?JSON.stringify(opts.body):undefined});if(!r.ok){let p=await r.json().catch(()=>({detail:"Request failed"}));throw Error(p.detail||"Request failed")}return r.json()}
async function init(){if(token){try{user=await req("/auth/me");await refresh()}catch(e){localStorage.removeItem("ttm_token");token=""}}render()}
async function refresh(){[projects,users,tasks,dash]=await Promise.all([req("/projects"),req("/users"),req("/tasks"),req("/dashboard")]); if(!selected&&projects[0]) selected=projects[0].id}
function project(){return projects.find(p=>p.id==selected)||projects[0]||null}
function canManage(p){return user&&p&&(user.role==="admin"||p.members.some(m=>m.user.id===user.id&&m.role==="admin"))}
function val(id){return document.getElementById(id).value}
async function auth(e){e.preventDefault();try{const body=mode==="signup"?{name:val("name"),email:val("email"),password:val("password"),role:val("role")}:{email:val("email"),password:val("password")};const res=await req(mode==="signup"?"/auth/signup":"/auth/login",{method:"POST",body});token=res.access_token;user=res.user;localStorage.setItem("ttm_token",token);msg="Welcome, "+user.name;await refresh()}catch(err){msg=err.message}render()}
async function createProject(e){e.preventDefault();try{const p=await req("/projects",{method:"POST",body:{name:val("pname"),description:val("pdesc")}});selected=p.id;msg="Project created";await refresh()}catch(err){msg=err.message}render()}
async function addMember(e){e.preventDefault();let p=project();try{await req("/projects/"+p.id+"/members",{method:"POST",body:{email:val("memail"),role:val("mrole")}});msg="Member added";await refresh()}catch(err){msg=err.message}render()}
async function createTask(e){e.preventDefault();let p=project();try{await req("/projects/"+p.id+"/tasks",{method:"POST",body:{title:val("ttitle"),description:val("tdesc"),priority:val("tpri"),due_date:val("tdue")?new Date(val("tdue")).toISOString():null,assignee_id:val("tuser")?Number(val("tuser")):null}});msg="Task created";await refresh()}catch(err){msg=err.message}render()}
async function setStatus(id,st){try{await req("/tasks/"+id,{method:"PATCH",body:{status:st}});msg="Status updated";await refresh()}catch(err){msg=err.message}render()}
function logout(){localStorage.removeItem("ttm_token");token="";user=null;projects=[];tasks=[];selected=null;render()}
function renderAuth(){document.getElementById("root").innerHTML='<main class="auth"><section class="hero"><div><p class="eyebrow">Team Task Manager</p><h1>Plan projects, assign work, and watch progress in one place.</h1><p>Full-stack project with authentication, SQL relationships, REST APIs and role based access for Admin and Member users.</p></div></section><section class="panel"><div class="tabs"><button class="'+(mode==="signup"?"on":"")+'" onclick="mode=\\'signup\\';render()">Signup</button><button class="'+(mode==="login"?"on":"")+'" onclick="mode=\\'login\\';render()">Login</button></div><form onsubmit="auth(event)">'+(mode==="signup"?'<label>Name<input id="name" required minlength="2"></label>':"")+'<label>Email<input id="email" type="email" required></label><label>Password<input id="password" type="password" required minlength="8"></label>'+(mode==="signup"?'<label>Role<select id="role"><option value="admin">Admin</option><option value="member">Member</option></select></label>':"")+'<button class="primary">'+(mode==="signup"?"Create account":"Login")+'</button></form>'+(msg?'<span class="msg">'+msg+'</span>':"")+'</section></main>'}
function renderApp(){let p=project(), manageable=canManage(p);document.getElementById("root").innerHTML='<main class="app"><header class="top"><div><p class="eyebrow">Team Task Manager</p><h1>Workspace Dashboard</h1></div><div class="profile"><span>'+user.name+'</span><b>'+user.role+'</b><button onclick="logout()">Logout</button></div></header><section class="metrics"><div class="metric"><span>Projects</span><b>'+dash.total_projects+'</b></div><div class="metric"><span>Tasks</span><b>'+dash.total_tasks+'</b></div><div class="metric"><span>Assigned to me</span><b>'+dash.assigned_to_me+'</b></div><div class="metric danger"><span>Overdue</span><b>'+dash.overdue+'</b></div></section><section class="grid"><aside class="side"><div class="head"><h2>Projects</h2></div><div class="projects">'+projects.map(x=>'<button class="'+(p&&p.id===x.id?"sel":"")+'" onclick="selected='+x.id+';render()"><b>'+x.name+'</b><span>'+x.members.length+' members</span></button>').join("")+(projects.length?"":'<p class="empty">Create your first project.</p>')+'</div><form onsubmit="createProject(event)"><input id="pname" placeholder="Project name" required minlength="2"><textarea id="pdesc" placeholder="Project description"></textarea><button class="primary">New project</button></form></aside><section class="main"><div class="head"><div><h2>'+(p?p.name:"No project selected")+'</h2><p>'+(p?(p.description||"Team, task and status controls appear here."):"Create a project to begin.")+'</p></div>'+(msg?'<span class="msg">'+msg+'</span>':"")+'</div>'+(p?manageHtml(p,manageable):"")+boardHtml(p)+'</section></section></main>'}
function manageHtml(p,manageable){return '<div class="manage"><div class="box"><h3>Team</h3><div class="members">'+p.members.map(m=>'<span>'+m.user.name+'<small>'+m.role+'</small></span>').join("")+'</div>'+(manageable?'<form class="inline" onsubmit="addMember(event)"><input id="memail" type="email" placeholder="member@email.com" required><select id="mrole"><option value="member">Member</option><option value="admin">Admin</option></select><button>Add</button></form>':"")+'</div>'+(manageable?'<form class="box taskform" onsubmit="createTask(event)"><input id="ttitle" placeholder="Task title" required minlength="2"><select id="tpri"><option value="low">Low</option><option value="medium" selected>Medium</option><option value="high">High</option></select><textarea id="tdesc" placeholder="Task details"></textarea><input id="tdue" type="datetime-local"><select id="tuser"><option value="">Unassigned</option>'+p.members.map(m=>'<option value="'+m.user.id+'">'+m.user.name+'</option>').join("")+'</select><button class="primary">Create task</button></form>':"")+'</div>'}
function boardHtml(p){return '<div class="board">'+Object.keys(status).map(s=>'<section class="col"><h3>'+status[s]+'<span>'+dash.by_status[s]+'</span></h3>'+tasks.filter(t=>t.status===s&&(!p||t.project_id===p.id)).map(t=>'<article class="card"><div class="row"><b>'+t.title+'</b><span class="pill '+t.priority+'">'+pri[t.priority]+'</span></div><p>'+(t.description||"No description added.")+'</p><div class="row meta"><span>'+(t.assignee?t.assignee.name:"Unassigned")+'</span><span>'+(t.due_date?new Date(t.due_date).toLocaleDateString():"No due date")+'</span></div><select onchange="setStatus('+t.id+',this.value)">'+Object.keys(status).map(x=>'<option value="'+x+'" '+(x===t.status?"selected":"")+'>'+status[x]+'</option>').join("")+'</select></article>').join("")+'</section>').join("")+'</div>'}
function render(){user?renderApp():renderAuth()}init();
</script></body></html>`;

http.createServer((req, res) => {
  res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
  res.end(html);
}).listen(3000, "127.0.0.1", () => {
  console.log("Team Task Manager local frontend: http://127.0.0.1:3000");
});
