services:
  - type: web
    name: build-team-task-manager
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: NEXT_PUBLIC_API_BASE_URL
        value: /api
      - key: DATABASE_URL
        value: sqlite:////tmp/team_task_manager.db
